webtalk_init -webtalk_dir C:/Users/gamin/VivadoWorkspace/FIR_filter/FIR_filter.sim/sim_1/behav/xsim/xsim.dir/FIR_blocks_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 25 22:19:38 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5366ad29-f587-4381-aaf3-5b7e7527a3ca" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "475a4e1784dc426e87d14c2291a6ccb5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "269" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "5 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7448_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1762905769 -regid "" -xml C:/Users/gamin/VivadoWorkspace/FIR_filter/FIR_filter.sim/sim_1/behav/xsim/xsim.dir/FIR_blocks_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/gamin/VivadoWorkspace/FIR_filter/FIR_filter.sim/sim_1/behav/xsim/xsim.dir/FIR_blocks_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/gamin/VivadoWorkspace/FIR_filter/FIR_filter.sim/sim_1/behav/xsim/xsim.dir/FIR_blocks_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
